# This workflow creates the required template files for the current day of Advent of Code
name: setup

# At 05:05 on every day from 1 through 24 in December.
on:
  schedule:
    - cron: "5 5 1-24 12 *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Run setup

      - name: Run setup
        run: ./gradlew getDayOfMonth setup -PSESSION_COOKIE=${{ secrets.SESSION_COOKIE }}

      # Commit changes

      - name: Commit and push bumped version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Generated files for day ${{ env.DAY_OF_MONTH }}